# Generated by Django 5.1 on 2025-06-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(default='', upload_to='voitures/'),
            preserve_default=False,
        ),
    ]
