# Generated by Django 5.1 on 2025-09-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='whatsapp_number',
            field=models.CharField(default='25776929167', max_length=20),
        ),
    ]
