# Generated by Django 5.1 on 2025-09-09 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_configuration_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='est_confirmee',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='lieu_depart',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='lieu_retour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.voiture'),
        ),
    ]
